In [99]:

f = open('itheima.txt','w')

f.close()


In [102]:
def name1():
    f=open('itheima.txt','r')
    read = f.read()
#     print(read)
    f.close()
    return read
exec(name1())

123
123
123


In [106]:
class Person(object):
    def move(self):
        print('人会行走')
xm = Person()
xm.move()
print(Person,id(xm))

人会行走
<class '__main__.Person'> 82475664


In [108]:
class Dog(object):
    def eat(self):
        print('狗会吃骨头')
a = Dog()
a.name = 'andy'
a.age = 6
a.height = 1
a.eat()
print('名字：%s\n年龄：%d\n高:%d' % (a.name, a.age, a.height))

狗会吃骨头
名字：andy
年龄：6
高:1


In [109]:
class Hero(object):
    def info(self):
        print(self.name)
        print(self.age)
        print(self.hp)
        print(self.atk)
wk = Hero()
wk.name = '悟空'
wk.age = 18
wk.hp = 3000
wk.atk = 200
wk.info()

悟空
18
3000
200


In [116]:
import numpy as np
a = np.arange(5)
a.dtype
a.shape

(5,)

In [123]:
m = np.array([np.arange(3), np.arange(3), np.arange(3)])
m.shape

(3, 3)

In [131]:
np.arange(7, dtype = 'D')

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [136]:
np.dtype('f8')

dtype('float64')

In [143]:
t = np.dtype([('name', 'str_', 40), ('numitems', 'int32'), ('price', 'float32')])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [148]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)],dtype = t)
itemz[1]

('Butter', 13, 2.72)

In [160]:
b = np.array(([0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]))
b.flatten()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [162]:
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [165]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [231]:
a = np.arange(9).reshape(3,3)
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [179]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [181]:
np.concatenate((a,b), axis =1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [182]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [185]:
oned = np.arange(2)
twice_oned = 2 * oned
np.column_stack((oned,twice_oned))

array([[0, 0],
       [1, 2]])

In [187]:
np.column_stack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [226]:
class MyList(list):
    def __mul__(self,number):
        for i in range(0,len(self)):
            self[i] *= 2
        return self
a = MyList(x for x in range(1,51)) * 2 
a

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [228]:
np.row_stack((oned, twice_oned)) 

array([[0, 1],
       [0, 2]])

In [232]:
np.vstack((a, b)) #纵向叠加

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [239]:
import re


Help on function compile in module re:

compile(pattern, flags=0)
    Compile a regular expression pattern, returning a pattern object.



In [256]:
m = re.match('foo','foo')
if m is not None:
    a=m.group()
a

'foo'

In [255]:
re.match('foo', 'foo is an ad').group()



'foo'